import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {notFound} from "next/navigation";
import AntdRegistry from "@/lib/AntdRegistry";
import {Footer} from "@/app/components/Footer/Footer";
import theme from "@/theme/themeConfig";
import {ConfigProvider} from "antd";
import React from "react";
import {NavBar} from "../components/NavBar/NavBar";
import StyledComponentsRegistry from "@/lib/Registry";

const locales = ["th", "en"];
const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter"
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                       params: {locale}
                                   }: {
    children: React.ReactNode,
    params: { locale: string }
}) {
    // Validate that the incoming `locale` parameter is valid
    if (!locales.includes(locale as any)) notFound();

    return (
        <html lang={locale}>
        <body className={inter.className}>
        <AntdRegistry>
            <ConfigProvider theme={theme}>
                <StyledComponentsRegistry>
                    <NavBar/>
                    <div className={"min-h-[calc(100vh-242px)]"}>
                        {children}
                    </div>
                    <Footer/>
                </StyledComponentsRegistry>
            </ConfigProvider>
        </AntdRegistry>
        </body>
        </html>
    );
}
